2026.04.12 스팀 댓글 페이지만 크롤링

commentthread_comment_text 출력되는지 테스트

In [ ]:
from bs4 import BeautifulSoup
import requests

url = "https://steamcommunity.com/app/367520/eventcomments/807972774925588882/"
res = requests.get(url)
soup = BeautifulSoup(res.text, "html.parser")

one_text = soup.find("div", class_="commentthread_comment_text")
text_title = one_text.text

print("one_text:", one_text)
print("text_title:", text_title) # 스팀 댓글 중에 이모티콘 있는게 있던데 공백으로 출력됨

one_text: <div class="commentthread_comment_text" id="comment_content_807972774925588933">
<img alt=":hollowknight:" class="emoticon" src="https://community.fastly.steamstatic.com/economy/emoticon/hollowknight"/> </div>
text_title:

댓글 창 한 페이지 분량만큼
반응 표시

In [ ]:
import requests
from bs4 import BeautifulSoup

# 스팀 이벤트에 대한 댓글 페이지
url = "https://steamcommunity.com/app/367520/eventcomments/807972774925588882/?ctp="

res = requests.get(url)
soup = BeautifulSoup(res.text, "html.parser")

comment_comment = soup.find_all("div", class_="commentthread_comment_text")
comment_name = soup.find_all("bdi")
comment_date = soup.find_all("span", class_="commentthread_comment_timestamp")

data1 = []
data2 = []
data3 = []

# 댓글 내용 리스트와 이름 리스트에 각각 저장
for n in comment_comment:
    data1.append(n.text.strip())
for m in comment_name:
    data2.append(m.text)
for o in comment_date:
    data3.append(o.text.strip())

print(data1)
print(data2)
print(data3)

data = {
    "댓글 내용": data1,
    "이름": data2,
    "날짜": data3
}

['', '+15 social credit', 'Hollow Knight update!!! yeahhhh', 'After all this time and you guys are still updating the game', 'FAAAAAAA FUNDAAAAAAAAAAAA!!!', 'yeeeeah', 'bros updating the game in the big 26 😭😭😭😭 (thank you)', 'Nice job updating hollowknight but try to focus on the silksong dlc', "keep updating team cherry i'm almost there...", 'WW', 'here to put my mark', 'my heros', '¡¿Otra actualizacion?! ¿¿¿acaso es una señal de que se viene el DLC de Silksong??? :0', 'Could it be that the DLC for silksong somehow connects to the original game? It is suspicious they are updating this so much.', 'mrrrow']
['borsdy', '𝔪𝔢𝔪𝔬𝔯𝔶', 'tofublockyy⚾', 'TanKLoveR', 'Lord of Cheese', 'bigzheka', 'federa', 'Jademan5', 'Milli', 'Styck', 'ƒiиorzã', 'MJ', 'Cord Clover', 'Namer', 'Blifi']
['Mar 26 @ 9:26pm', 'Mar 26 @ 9:29pm', 'Mar 26 @ 9:29pm', 'Mar 26 @ 9:35pm', 'Mar 26 @ 9:37pm', 'Mar 26 @ 9:37pm', 'Mar 26 @ 9:39pm', 'Mar 26 @ 9:39pm', 'Mar 26 @ 9:41pm', 'Mar 26 @ 9:42pm', 'Mar 26 @ 9:42pm', 'Mar 26 @ 9:44pm', 'Mar 26 @ 9:44pm', 'Mar 26 @ 9:44pm', 'Mar 26 @ 9:45pm']

In [ ]:
# 데이터 프레임으로 변환
import pandas as pd

df = pd.DataFrame(data)
df.to_csv("스팀 반응.csv")
print(df)

                                                댓글 내용              이름  \
0                                                              borsdy
1                                   +15 social credit          𝔪𝔢𝔪𝔬𝔯𝔶
2                     Hollow Knight update!!! yeahhhh    tofublockyy⚾
3   After all this time and you guys are still upd...       TanKLoveR
4                        FAAAAAAA FUNDAAAAAAAAAAAA!!!  Lord of Cheese
5                                             yeeeeah        bigzheka
6   bros updating the game in the big 26 😭😭😭😭 (tha...          federa
7   Nice job updating hollowknight but try to focu...        Jademan5
8       keep updating team cherry i'm almost there...           Milli
9                                                  WW           Styck
10                                here to put my mark         ƒiиorzã
11                                           my heros              MJ
12  ¡¿Otra actualizacion?! ¿¿¿acaso es una señal d...     Cord Clover
13  Could it be that the DLC for silksong somehow ...           Namer
14                                             mrrrow           Blifi

                 날짜
0   Mar 26 @ 9:26pm
1   Mar 26 @ 9:29pm
2   Mar 26 @ 9:29pm
3   Mar 26 @ 9:35pm
4   Mar 26 @ 9:37pm
5   Mar 26 @ 9:37pm
6   Mar 26 @ 9:39pm
7   Mar 26 @ 9:39pm
8   Mar 26 @ 9:41pm
9   Mar 26 @ 9:42pm
10  Mar 26 @ 9:42pm
11  Mar 26 @ 9:44pm
12  Mar 26 @ 9:44pm
13  Mar 26 @ 9:44pm
14  Mar 26 @ 9:45pm

댓글 창 페이지를 모두 탐색하고 댓글을 모두 리스트에 저장하기 위해...

우선 스팀 댓글 페이지를 나타내는 엘리먼트를 찾는다

In [ ]:
from bs4 import BeautifulSoup
import requests

url = "https://steamcommunity.com/app/367520/eventcomments/807972774925588882/"
res = requests.get(url)
soup = BeautifulSoup(res.text, "html.parser")

comment_count = soup.find("div", class_="forum_paging_summary ellipsis")
comment_max = comment_count.text.strip()

print("one_text:", comment_max)
print("one_text:", comment_max.split()[3]) # 문자열을 쪼개서 리스트로 만들고 꺼내는 방식

one_text: Showing 1-15 of 207 comments
one_text: 207

In [74]:
import requests
from bs4 import BeautifulSoup

# 스팀 이벤트에 대한 댓글 페이지
url = "https://steamcommunity.com/app/367520/eventcomments/807972774925588882/?ctp="
ctp = 1 # ctp = 댓글 페이지 수

res = requests.get(url+str(ctp))
soup = BeautifulSoup(res.text, "html.parser")

# 댓글 페이지 수 계산
comment_count = soup.find("div", class_="forum_paging_summary ellipsis")
comment_max = comment_count.text.strip()
comment_page = int(comment_max.split()[3])//15 + 1 # comment_max.split()[3] = 207은 문자열
# 스팀 공지 페이지랑 댓글 페이지 보면 공지는 Showing 1-15 of 21 active topics, 댓글은 Showing 1-15 of 214 comments 이런 식으로 공지 수랑 댓글 수가 몇 개인지 보이는데 둘 다 띄어쓰기 기준으로 쪼개면 3번째 인덱스가 최대 갯수임.
# 한 페이지당 최대 댓글 수가 15개인 걸 이용하여 214/15 이런 식으로 몫을 계산하여 댓글(몫) 페이지 수를 계산, 댓글이 15개보다 적을 경우를 대비해 1을 더해줌-> ctp는 0이 아니라 1부터 시작하기에

data1 = []
data2 = []
data3 = []

# 댓글 페이지 수 만큼 반복하여 리스트에 댓글 정보를 저장하는 반복문
for i in range(comment_page):

    comment_comment = soup.find_all("div", class_="commentthread_comment_text")
    comment_name = soup.find_all("bdi")
    comment_date = soup.find_all("span", class_="commentthread_comment_timestamp")

    # 댓글 내용 리스트와 이름 리스트에 각각 저장
    for n in comment_comment:
            data1.append(n.text.strip())
    for m in comment_name:
            data2.append(m.text)
    for o in comment_date:
            data3.append(o.text.strip())

    # 변동되는 ctp에 따라 다시 크롤링 하는 페이지 재정의
    ctp += 1
    res = requests.get(url+str(ctp))
    soup = BeautifulSoup(res.text, "html.parser")



print("데이터 개수:",len(data1))
print(data1)
print(data2)
print(data3)

data = {
    "댓글 내용": data1,
    "이름": data2,
    "날짜": data3
}
print(type(data))
print(data)

데이터 개수: 214
['', '+15 social credit', 'Hollow Knight update!!! yeahhhh', 'After all this time and you guys are still updating the game', 'FAAAAAAA FUNDAAAAAAAAAAAA!!!', 'yeeeeah', 'bros updating the game in the big 26 😭😭😭😭 (thank you)', 'Nice job updating hollowknight but try to focus on the silksong dlc', "keep updating team cherry i'm almost there...", 'WW', 'here to put my mark', 'my heros', '¡¿Otra actualizacion?! ¿¿¿acaso es una señal de que se viene el DLC de Silksong??? :0', 'Could it be that the DLC for silksong somehow connects to the original game? It is suspicious they are updating this so much.', 'mrrrow', 'How wonderful that this beauty is still being pampered.', 'ohhh,yeah', 'Team Cherry, I beg you, PLEASE remove STAG station sign in front of TRAM station in Resting Grounds, I cannot live with it', '"Fixed Radiance\'s orb attack hitbox lingering slightly longer than intended if the orb expires in the air." Thanks and this is my fav game ever but also ♥♥♥♥♥♥♥♥♥ why did this take 9 years to fix, the amount of deaths to this is insane 💀', 'After all of this and you still give us update, plis let us spay you more or wathever😭', 'Can you now please fix Silk Song being a stupid game? ❤️', 'Team Cherry still updating their game after years really show how passionate they were with the game. W', 'More bug fixes :3', 'it´s amazing how the devs are still updating hk to be a better experience after all these years', 'BROOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO oh nice update', 'YAYYYYY HEAVY FOOLS ARE NO LONGER STUPEED!!', 'meow', 'marcando presença', 'best devs', 'Where is hollow knight 2 ive been waiting 6 years', "This game is actually so terrible. The fact they still making updates to this bad game baffles me. Anyway... please don't check my favorite game on steam profile.", 'nice', '', 'we still getting pretty good uptades its insane', 'cool as hell to see them still updating this game. They do care. Someday silksong will come out.', '', 'Glad to see the game still being updated in this 26', '', '新增繁中? 真的假的?!', 'Додайте українську мову', 'YAY :3', 'Guys, please release Sea of Sorrow already. WE ARE STARVING.Jokes aside tho, thank you for still caring about the original Hollow Knight after all these years, have a blessed day <3', 'Radiance lingering orbs fixed. WOW!', 'W bugfix', 'ok', 'Originally posted by Memory:+15 social credit Social credit for traditional chinese? No.', 'PLEASE ADD !!!!!UKRAINIAN!!!!! LANG INTO GAME, LAST VERSION YOU CAN PICK FROM GUIDE', 'gitgud', 'Wow, +rep for still updating', "Gee, I can't wait until a new bepinex version with support for the new hk version drops", 'HAPPY HAPPY HAPPY', 'glad theres still active hollow knight players after peaksong', 'Lol', 'I just started another playthrough.Thank you.', 'I might just be unlucky, cus they still hit me above screen. rip', '67', 'Of course they fix the Radiance orb attack after I already beat her on radiant😭(still happy you fixed it guys good job)', "oh that's why sometimes Journal notification icons not appearing i thought i was tripping", 'Busy on Mewgenics but I appreciate', '+15 social credit', 'When the update for game graphics?', 'игра еще жива', '总之，继续努力吧', '', 'well how about co-op?', 'radiance fix in the year of 2026 omg', 'исправили пропажу названия локации при первом входе?', 'good job you ovesly still care about this game', 'i thought the heavy fool thing was intentional it happens loads', 'когда длс?', 'Huhu wow', 'Hey Developer, I can help you with Turkish language support; I can translate the texts.', "Can you guys also make the Grimm Child shut up like you did for Saluba's Blessing?", 'Team cherry deciding they need to fix a few stuff in hollow knight in 2026 (the silksong dlc is being developed)Pretty ♥♥♥♥♥♥♥ based though.', 'we love you, Team Cherry', 'Got a whole sequel out and STILL improving the first game. Respect!', 'молодцы!', 'HK ON TOP', 'where is sea of sorrow', 'JUST GIVE US A NEW HK DLC PLEASE', '翻译添加了中文翻译功能。 修复了在浏览物品栏时音频音量过低的问题。 修复了当宽方块键（如 Shift、空格等）被绑定到某个动作时，文本对齐问题，避免文本重叠。 修复了在特定情况下，过度附魔的凹槽会被意外移除的问题。 修复了如果光球在空中消散，“光辉”技能的球体攻击范围会比预期持续更长时间的问题。 修复了被感染的气球可以推动“魔爪兽”的问题。 修复了“螳螂叛徒”在地下时仍可受到伤害的问题。 修复了日志通知图标有时不显示，或者偶尔显示错误图标的问题。 修复了“新建日志条目”弹窗有时不显示的问题。 修复了一些情况下猎人笔记击杀奖励未能按预期发放的问题。 修复了“巴德尔护盾”有时持续时间比预期更长的问题。 修复了播放正确音效时出现双倍伤害的问题（之前播放的是单倍伤害音效）。 修复了“愚者冲刺”攻击有时无法达到最大距离的问题。 进行了多项性能优化。 修复了一些小问题。', 'finally!! radiance now is a perfect fight', 'so good, i closed HK on all achievements. BUT, why so much updates of first part? D:', 'Please repair my favorite fast spell button "\\" i can\'t set this button on settings 😓', 'bing chilling', 'Please add Turkish language support as well.', 'Update Broke My game?So when i try to run hollow knight it keeps crashing.', 'W', 'Please add the Arabic language', 'yeah', '2 updates is a year, we are eating good', "Fixed Journal notification icons sometimes not appearing, and occasionally displaying the incorrect icon.Fixed various instances of the 'New Journal Entry' pop-up not displaying.Genuinely a bug that has annoyed me for a decade", 'может cyка моды пофиксите?', "For so many years, it was possible to add Ukrainian a long time ago. There has long been a Ukrainianizer that could have been added as an official one. Just agree with the translators and that's it, but we shouldn't ignore all these years people who want Ukrainian to be added to the game. But we won't add traditional Chinese, and we will ignore all other languages.", 'Me: CRAZY, we love seeing Hk still being cared forMy imaginary cat: mrrp~...Maestro: VOLARIS!', 'siiiiii', 'good', 'please add Ukrainian translation', "Now we will see less posts of people dying to Abs Rad's last phase thanks to an orb not timing out properly.They are kinda entertaining, but still painful to watch, especially now that I've done it myself.", 'never expected an update in 2026', 'WUHU~', 'silksong when', 'че', '', 'thank you very much', "Amazing that they're continuing to update their first game when they could be focusing on the newest one. Both games will never die now", 'Some decent changes. I have to wonder how many improvements Team Cherry intends to make to HK still. Appreciated nonetheless.', 'Radiance ball fix is hype!', '', 'TC is spoiling us', 'Amazing <3', 'Team Cherry the GOAT', 'love u guys', '+10000 credito social a team cherry', '', 'TC doing side quests still. Nice.', "We're still getting updates 🥹", "I'm hollowing my knight as we speak", 'TEAM CHERRY IS THE GOAT', 'tuff', "I honestly thought quieter music in inventory was a feature. I wouldn't mind having it toggleable.", 'уже вижу как люди с нетрадиционной китайской ориентацией становятся натуралами', 'Where can you find mods that change how The Knight looks? I really want to use a mod!', 'Finally I can play the  game', 'Yessss. MOREEE!!!', 'chinese overlords pleasing quota', 'Pablo 🗿', 'LETS GOOOOOOOOOOOOOOOOOOOOOOOOOOOOO', 'Muchas gracias, solo espero que estas actualizaciones de HK, equivalgan al progreso de The hunter chocolatier...', "Let's gooooooooooo", '', 'Originally posted by Lord of Cheese:FAAAAAAA FUNDAAAAAAAAAAAA!!! :dungdefender: sup', 'Thanks!', "Honestly, the only thing I want are the Maggots not being needed for the Hunter's Journal. I dont want to hurt those poor souls.", 'hollow knight still live', 'They really just did Radiance easier', 'I was foolish enough to say "I\'ll 112% Hollow knight pre-silksong dlc because I\'ve been playing half a year!"...  Procrastination', '*sigh* Bapanada', '', '終於有繁體中文了 愛死你了', 'Good', 'W update', "People know social credit jokes but don't know they use Simplified Chinese?It's -15 social credit for adding Traditional Chinese", 'Please fix thisthe nail smith animation wont work and when i try to upgrade my nail its just a black screen with nothing happening preventing me from upgrading my nail.', 'i think that means that you cant do the bauldur shell strategy on radiance climb phasewhich is interesting (also W team cherry for not forgetting about hollow knight)', 'not silk song updat pek', 'pls fix traitor lord walk bug', '謝謝正體中文👍補丁版本 1.5.12620 現已上線更新說明新增了繁體中文翻譯修正了瀏覽物品欄時音量過低的問題。修正了文字對齊問題，當寬方形鍵（Shift/空白鍵等）綁定到某個操作時，文字不會重疊。修正了在特定情況下意外移除過度裝飾凹槽的問題。修正了輻光之球在空中消失時，其攻擊判定框停留時間比預期稍長的問題。修正了感染氣球可以推動噬魂怪的問題。修正了螳螂叛徒在地下時會被損壞的問題。修正了日誌通知圖示有時不顯示，偶爾顯示錯誤圖示的問題。修正了「新日記帳分錄」彈出視窗無法顯示的各種問題。修正了獵人筆記擊殺未如預期獎勵的個別情況。修正了 Baldur Shell 實例有時會停留時間過長的問題。修正了雙重傷害播放正確音訊片段的問題（之前播放的是單次傷害音效）。修正了重型愚者的衝刺攻擊有時無法到達全程的問題。多項性能改進。進行了各種小修復。', "plz team cherry, i want my skin to be used again! there's a file that says disabled and whenever i delete it, the mods don't work still. i really do love you guys and your games but plz, fix this", 'Originally posted by Namer:Could it be that the DLC for silksong somehow connects to the original game? It is suspicious they are updating this so much. Who is going to tell them what happens in the true ending of the game where hornet (does a cool thing) & beats the crap out of (a cool boss) while they are (in a skatepark)', 'Massive respect for reducing file size, if only other developers cared as much.', 'thx i rlly needed trad Chinese So i Can Ching Chen Hanji', 'Esto es una señal de un DLC de silksong, lo sé 🗣', 'Is there a reason why you haven’t added a Turkish language option to your game, which is purchased by many people in Turkey?', "Jesus loves y'all, have a good day", 'bro is STILL UPDATEING!', "an HK updated in the big '26??", "still a glitch where you can miss the hunter's journal entry for the False Knight false knight if you skip finishing him off at first. but good to see the bug fixes", "I loved how they didn't even put a spoiler filter for boss names because they know we already played too much of this game lmao", '也不知道用手柄操作冲刺的时候延迟解决了没有', 'W', "On a Mac, the sprint key frequently malfunctions. Is there a way to fix this? This problem doesn't exist in Silk Song.", 'Thank you for your continued support of Hollow Knight, Team Cherry', 'Polish language when?', '', "nooo i cant play the game anymore because i'm on macos 10.15 bruhhhh", 'nice.', 'Thanks Team Cherry, but when do you add alternate costume to Grimm that changes his look to a maid suit?', 'porque no me funciona el mando con este juego', 'An update to hollow knight in 2026, bug fixes are so fun :D:quirrel:', 'Even after all this time they updated it', "They nerfed Absolute Radiance so I'm happy, those orbs are the bane of my existence.", 'This patch breaks compatibility with the Xbox-compatible controller', "Bro the heavy fool bug has been bothering me for ages so glad that's finally getting fixed", 'Its causing a lot of stuttering on a mac m4, previous version was perfecly fine.', '', 'stop cooking with the updates lemme play with mods 😭', 'Oh wow, siguen las actualizaciones. Pues esto es excelente, qué gran Team!, qué gran Juego. Muchas gracias por seguir mantiniendo este juego con vida!', 'they took away Mawlurk push ;-;I would make a point every time I was there to push the mawlurk even if it risked of my steel soul run ;-;', 'love', 'w update heavy fool now doesnt trip constantly', 'Originally posted by Namer:Could it be that the DLC for silksong somehow connects to the original game? It is suspicious they are updating this so much. Yo, you might be onto something...', 'Originally posted by Jony12:porque no me funciona el mando con este juego A mi tampoco. Tuve que instalar la versión anterior.', 'so cool bro but i need a new boss y pls update silksong', 'Traditional Chinese translation 🤩Thank you~~~', 'nice', 'Me parece genial que actualicen el juego, pero ¿soy el único al que el audio ya no le funciona después de la actualización?Edit: Solo tuve que resetear el audio en el menú del juego para arreglarlo. Un juegazo 10/10.', 'now we gotta wait more for lumafly to start workin again :D', "nice i'll play in china", 'Traditional Chinese! Finally!', 'yapi', 'everything but releasing sea of sorrow', 'Still getting updates after 7 years is crazy', '666', 'Thanks for your traditional chinese update!', 'a ustedes tambien les falla el mando al jugar? o solo a mi?', "Originally posted by Pumpkin lit via mini Bible:Jesus loves y'all, have a good day Hail Satan", 'w upd', 'no, i wasnt coming on hollow knight t find this. :) yey', 'As a dedicated fan of Hollow Knight, I truly admire the art and depth of the game. However, it\'s disappointing to see languages like Traditional Chinese added while the Arabic-speaking community is overlooked.\u200bWe are a vast and growing audience that appreciates high-quality indie games. Having the game in Arabic would significantly enhance our immersion and enjoyment of the lore. Please consider adding Arabic support in your upcoming projects (like Silksong). Your Middle Eastern fans are waiting!"', 'Meh, es una adicción', 'Please add Thai language.', '', 'I bought Hollow Knight twice. Once at GOG.com, once at Steam. You deserved it both times.', 'As a Taiwanese fan, thanks for the super late translation update lol Love this game!', "it might be from the previous update but I can no longer see the percentage of game completion I am at. I wanted my first play through to be 112% and now I don't know how far I am from my goal...  :,(", '好', 'like like', "Jesus loves y'all, have a good day", 'Siguen agregando idiomas y arreglando bugs. Aprendé, Toby Fox.', 'Has anyone been having controller connection problems after the hot fix? My xbox controller will work like usual just to keep disconnecting for a few second every few seconds', "Originally posted by Ozymandias:Originally posted by Pumpkin lit via mini Bible:Jesus loves y'all, have a good day Hail Satan :ZAT_Pentagram: Jesus loves you", 'У меня после этой обновы в Зеленой тропе на пути к Шео в комнате с паркуром тупо игра не реагирует почти ни на какие действия! Прошу исправьте это недоразумение', 'keep updating, but half the community will keep themselves in 1.2.2.1, as always.']
['borsdy', '𝔪𝔢𝔪𝔬𝔯𝔶', 'tofublockyy⚾', 'TanKLoveR', 'Lord of Cheese', 'bigzheka', 'federa', 'Jademan5', 'Milli', 'Styck', 'ƒiиorzã', 'MJ', 'Cord Clover', 'Namer', 'Blifi', 'Gunaraj', 'Asamo', 'dovolniybomj39815', 'Raynestorm', 'Nijiker', 'Kars-T', 'bunbun_69', 'Bird_potato', 'Blck', 'dreamoftheage', 'EnPassant', 'H3atHaze', 'Nika', 'Faded', 'Cookie', 'Quake3452', 'Locke', 'Kirikos', 'Jeager144', 'drtbkrder3', 'Aya2nd', 'SonicfanBD', '404NowheresNotFound.', '刀刻塔星雨', 'newalienfromla', 'SanGoldStorm', 'Clover', 'TheExtropian', 'HelixTheCreator', '芒果大帝玩蒸汽', 'telfoid', 'UKRAЇNIAN', 'มูหมา_หมาเห่า', 'Sanyanders', 'Gr477F_1225', 'lixo', 'skibidi ronaldo', 'YASMARINA', '23', 'Maximilion13', 'Mod', 'SuperHerobrine1', 'wawaok', 'class101 [ѕtеαмdеcκ]', 'のあ先先輩', 'Синявенький', 'TheYuri4amba', '南孚', 'мартиросян', 'Say10', 'Underpaid Assistant', 'мартиросян', 'harrisonlikesfanf', 'PowerTracker', '_awery__', 'Strike-Team', 'Strike-Team', 'Max207', 'Onyx', 'Pie', 'RenegadeNic', 'vladislav99lv', 'mimicry\ue008', 'neon acid', '7Maze7', 'planet', 'Rossi', 'YourWywern', 'ninjaelwinzo', 'Praeludium', 'FearlesCriss', 'Feesh', 'Виктор', 'BEZ', '76561199231216639', 'sonimbleini', 'rolandoftheeld', 'ᴛᴇʍный ᴨᴩинц♫', 'Сірий Пес', 'Amendobobo', 'Inexluna', '教授', 'Stacy Malibu', 'Gumpers08', '76561199876176967', '日月如风', 'funnyfunnyfunny', 'взаимная похвала', 'AhmadF89', 'Gnuffe', 'HooHa34', 'Heshlak', 'Gryphon', 'Wombo_Combo', 'crownewreck', '𝖓𝖊𝖇𝖚', 'Dezozlesa', 'DanDio', 'Mrttomate0203', '먼지', 'Zijkrial', 'SenatorTheTurkey', 'Jabba the Hutt', 'CY13ERPUNK', 'Whale shark', 'AbsoluteVacuum', 'SMILE D0G', 'AKK', 'SanStar', 'Bliky', 'Apolo', 'Mysma', 'moodsta', '1nk123nk', 'Yugentsuki', 'AlexFG', 'the roaring (demo)knight', 'BernyMoon', 'shadow 888', 'braia', 'thirteen', 'Random User', 'Waggleton', 'i am dmitro', 'A5reiko', 'теневой призрак', 'Potepto', 'eska', 'PandaMan', 'ash woosh the wierd', 'HAP1031', 'Croissant', 'Pickle', 'jayden.grisafi', 'Spider in Laptop', 'Malcolm_Wren', 'LocalGamist', '76561199883851525', 'Mahmut Dönmez', 'Pumpkin lit via mini Bible', 'The_Hollowmon', 'WY', 'Slive', 'Preon', '1326015559', 'quietOrca', '来日可期Felix', 'Jean', 'proletarius87', 'FlailoftheLord', '76561198776796511', 'Rip_Sukuna12', 'pancake enthusiast', 'Jony12', 'Lumice', 'AdamHartGaming', 'VampireKink12', 'SolracCeam', 'Smile', 'italocjs', 'meoweineee', 'just_Dima', '.z0o.', 'Hex: Catboy', 'KLITOR', 'The90sgamer', 'dtbrox', 'SolracCeam', 'adrikcarrizozad', 'ChiaBurn', 'GeordiLund', 'leonarotti', 'passenger_mc', 'fougere.violette', 'StarYazmin', 'Lekku', 'Арбуъ', 'Lobotomophobia', 'thdofk', 'Giz', 'Jony12', 'Ozymandias', 'the hollow knight', 'lilmaedob', 'imoD', 'Pach', 'AOM', 'Hugrage', 'KZiemian', 'Stella1011', 'veratopchev', '遮羞艾莉', 'Bogapequeno', 'Pumpkin lit via mini Bible', 'BetrayedByYourMind', 'ToastedXZ', 'the guy from home alone', 'Ketziro', 'elephante_91p']

In [75]:
# 데이터 프레임으로 변환하고 csv 파일로 저장까지
import pandas as pd

df = pd.DataFrame(data)
df.to_csv("스팀 반응.csv")
print(df)
df.head()

                                                 댓글 내용  \
0
1                                    +15 social credit
2                      Hollow Knight update!!! yeahhhh
3    After all this time and you guys are still upd...
4                         FAAAAAAA FUNDAAAAAAAAAAAA!!!
..                                                 ...
209  Siguen agregando idiomas y arreglando bugs. Ap...
210  Has anyone been having controller connection p...
211  Originally posted by Ozymandias:Originally pos...
212  У меня после этой обновы в Зеленой тропе на пу...
213  keep updating, but half the community will kee...

                          이름               날짜
0                     borsdy  26 Mar @ 9:26pm
1                     𝔪𝔢𝔪𝔬𝔯𝔶  26 Mar @ 9:29pm
2               tofublockyy⚾  26 Mar @ 9:29pm
3                  TanKLoveR  26 Mar @ 9:35pm
4             Lord of Cheese  26 Mar @ 9:37pm
..                       ...              ...
209       BetrayedByYourMind  16 Apr @ 8:29pm
210                ToastedXZ  17 Apr @ 4:52pm
211  the guy from home alone  19 Apr @ 4:15pm
212                  Ketziro  20 Apr @ 8:37am
213            elephante_91p  24 Apr @ 8:42am

[214 rows x 3 columns]

,댓글 내용,이름,날짜
0,,borsdy,26 Mar @ 9:26pm
1,+15 social credit,𝔪𝔢𝔪𝔬𝔯𝔶,26 Mar @ 9:29pm
2,Hollow Knight update!!! yeahhhh,tofublockyy⚾,26 Mar @ 9:29pm
3,After all this time and you guys are still upd...,TanKLoveR,26 Mar @ 9:35pm
4,FAAAAAAA FUNDAAAAAAAAAAAA!!!,Lord of Cheese,26 Mar @ 9:37pm

스팀 공지는 이미 공지 크롤링 예시처럼 하면 크롤링 쉬울 것 같고 페이지 달라지는 댓글 크롤링 부분만 알고리즘 작성한거

리스트를 많이 만들어서 메모리를 많이 차지함

스팀 이모티콘은 공백으로 표시되어 없는 것처럼 보일 수 있음

2026.04.28  
스팀 공지 목록들과 댓글 페이지 동시 크롤링

In [24]:
import requests
from bs4 import BeautifulSoup

# 스팀 이벤트&공지에 대한 페이지
game_id = 367520 # 스팀 할로우 나이트 페이지의 고유 게임 id. 스팀 공지 링크 보면 https://steamcommunity.com/app/367520/eventcomments/ 이렇게 되어있는데 3번째꺼. 다른 게임 가져올거면 game_id만 바꾸면 됨
url_official = "https://steamcommunity.com/app/"+str(game_id)+"/eventcomments/?fp="
fp = 1 # fp = 이벤트&공지 페이지 수. 나중에 공지 긁는 기간을 늘리려면 ctp 조정했던 것 처럼 fp 조정으로 가능.
# fp 변수를 url_official에 붙일까 생각도 해봤는데 나중에 url 바뀔 때마다 url을 재정의해야해서 더 귀찮아짐. 나중에 게임 여러개 크롤링할 때는 game_id도 다르게 작성해야할 듯함

res_official = requests.get(url_official+str(fp))
soup_official = BeautifulSoup(res_official.text, "html.parser")

# 공지 페이지 수 계산
official_count = soup_official.find("div", class_="forum_paging_summary ellipsis")
official_max = official_count.text.strip()
official_page = int(official_max.split()[3])//15 + 1 # comment_max.split()[3] = 21 은 문자열

news_steam = soup_official.select_one(".forum_topics").select("a") # div 클래스 forum_topics 를 불러오고 그 안의 a 태그 안의 내용을 가져옴

data = []

# 공지사항 제목과 링크 가져오기
for i in news_steam:
    official_link = i.get("href") # a 태그 안의 href 링크를 가져옴
    if official_link: # 링크가 존재한다면
        data.append(official_link) # 링크를 리스트에 추가

print(data)

['https://steamcommunity.com/app/367520/eventcomments/807972774925588882/', 'https://steamcommunity.com/app/367520/eventcomments/756176763055374323/', 'https://steamcommunity.com/app/367520/eventcomments/1636418037462792359/', 'https://steamcommunity.com/app/367520/eventcomments/3115920924803533010/', 'https://steamcommunity.com/app/367520/eventcomments/3455969319451574967/', 'https://steamcommunity.com/app/367520/eventcomments/3048356136506952319/', 'https://steamcommunity.com/app/367520/eventcomments/1636418037467089906/', 'https://steamcommunity.com/app/367520/eventcomments/3109152828489633510/', 'https://steamcommunity.com/app/367520/eventcomments/1636418037463443416/', 'https://steamcommunity.com/app/367520/eventcomments/1636418037463920770/', 'https://steamcommunity.com/app/367520/eventcomments/1636418037467089899/', 'https://steamcommunity.com/app/367520/eventcomments/1636418037467089894/', 'https://steamcommunity.com/app/367520/eventcomments/1636418037463640937/', 'https://steamcommunity.com/app/367520/eventcomments/1636418037466907251/', 'https://steamcommunity.com/app/367520/eventcomments/3048356136495645181/']

우선 스팀 공지 페이지의 공지 링크들을 하나하나 리스트에 저장, 데이터패널 형식이라 공지 이름은 따기 어려워서 뒤에 딸 예정

스팀은 공지 내용이 있는 상세 페이지로 따로 들어갈 수 있음. 게임 라이브러리에서 보이는 그거. 내용은 거기서밖에 따올 수 없어서 또 링크를 새로 파야됨

In [43]:
import requests
from bs4 import BeautifulSoup

url = "https://steamcommunity.com/app/367520/eventcomments/807972774925588882/?ctp=1"

res = requests.get(url)
soup = BeautifulSoup(res.text, "html.parser")

#link_get = soup.select_one(".maincontent").find("div",class_="content") # 시행착오 테스트용. href가 들은 a 태그를 찾음 bb_link
link_get = soup.find("a",class_="bb_link").get("href") # a 태그 안의 href 링크 불러오기
# links = [] 전에 했던 방법으로 a 태그 불러오려 하는데 왜인지 안됨...
# for i in link_get:
#     detail_link = link_get.get("href")
#     if detail_link:
#         links.append(detail_link)
print(link_get)

https://steamcommunity.com/ogg/367520/announcements/detail/529875497931243581

이제 링크 속 공지 제목이랑 내용 따기

In [71]:
import requests
from bs4 import BeautifulSoup

url = "https://steamcommunity.com/games/367520/announcements/detail/529875497931243581"

res = requests.get(url)
soup = BeautifulSoup(res.text, "html.parser")
# print(soup.prettify()) 얘로 태그 찾기 쉽네
title_detail = soup.find("title").text # 결과 Steam :: Hollow Knight :: Patch Version 1.5.12620 Now Live
title_detail = title_detail.split("::") # :: 기준으로 쪼개면 3개의 요소가 있는 리스트가 만들어짐
title_detail = title_detail[2] # 리스트의 두번째 인덱스인 제목을 값으로 저장

content_detail = soup.find("meta", {"name": "Description"}).get("content") # 공지 내용은 메타 태그로 저장되어 있음. 페이지 소스 보기로 확인 가능

print(title_detail)
print(content_detail)

 Patch Version 1.5.12620 Now Live
Patch Notes Added Traditional Chinese translation Fixed low audio volume when navigating the inventory. Fixed alignment for text to not overlap when a wide square key (shift/space/etc) is bound to an action. Fixed overcharmed notches being unintentionally removed in a specific instance. Fixed Radiance's orb attack hitbox lingering slightly longer than intended if the orb expires in the air. Fixed Mawlurks being pushable by Infected Balloons.

공지와 댓글 같이 저장하기

In [82]:
import requests
from bs4 import BeautifulSoup

# Chapter 1: 공지 링크들 따기 start
# 스팀 이벤트&공지에 대한 페이지
game_id = 367520 # 스팀 할로우 나이트 페이지의 고유 게임 id. 스팀 공지 링크 보면 https://steamcommunity.com/app/367520/eventcomments/ 이렇게 되어있는데 3번째꺼. 다른 게임 가져올거면 game_id만 바꾸면 됨
url_official = "https://steamcommunity.com/app/"+str(game_id)+"/eventcomments/?fp="
fp = 1 # fp = 이벤트&공지 페이지 수. 나중에 공지 긁는 기간을 늘리려면 ctp 조정했던 것 처럼 fp 조정으로 가능. fp 변수를 url_official에 붙이려 해봤는데 나중에 url 바뀔 때마다 url을 재정의해야해서 오히려 귀찮아짐. 나중에 게임 여러개 크롤링할 때는 game_id 도 fp처럼 따로 빼야할 듯

res_official = requests.get(url_official+str(fp)) # url을 불러옴, fp 는 몇번째 페이지인지를 나타내기에 나중에 여러 페이지를 불러온다면? 을 생각해서 일단 만들어 놓음
soup_official = BeautifulSoup(res_official.text, "html.parser")

# 공지 페이지 수 계산
official_count = soup_official.find("div", class_="forum_paging_summary ellipsis")
official_max = official_count.text.strip()
official_page = int(official_max.split()[3])//15 + 1 # comment_max.split()[3] = 21 은 문자열

news_steam = soup_official.select_one(".forum_topics").select("a") # div 클래스 forum_topics 를 불러오고 그 안의 a 태그를 가져옴

official_links = []

# 공지사항 제목과 링크 가져오기
for a in news_steam:
    link = a.get("href") # a 태그 안의 href 링크를 가져옴
    if link: # 링크가 존재한다면
        official_links.append(link) # 링크를 리스트에 추가

# Chapter 1: 공지 링크들 따기 end
# Chapter 2: 공지 제목과 내용 따기 start

data = []

for links in official_links: # official_links 리스트 안의 링크들 하나씩 불러와서 링크들을 전부 호출하면 반복문 종료
    # 스팀 이벤트에 대한 댓글 페이지. 공지 링크가 바뀔 때마다 재정의
    url_unit = links + "?ctp="
    ctp = 1 # ctp = 댓글 페이지 수

    res_unit = requests.get(url_unit+str(ctp)) # 얘는 댓글 추출용으로 공지 내용이 간소화된 페이지
    soup_unit = BeautifulSoup(res_unit.text, "html.parser")

    detail_link = soup_unit.find("a",class_="bb_link").get("href") # 상세 페이지 진입을 위한 href 링크가 들어있는 a 태그를 불러오고 href 링크를 가져오고 저장
    res_detail = requests.get(detail_link) # 얘는 공지 내용 추출용으로 상세 공지 내용이 적힌 페이지
    soup_detail = BeautifulSoup(res_detail.text, "html.parser")

    title_detail = soup_detail.find("title").text # 결과 ex) Steam :: Hollow Knight :: Patch Version 1.5.12620 Now Live
    title_detail = title_detail.split("::") # :: 기준으로 쪼개면 3개의 요소가 있는 리스트가 만들어짐
    title_detail = title_detail[2] # 리스트의 두번째 인덱스인 제목을 값으로 저장

    content_detail = soup_detail.find("meta", {"name": "Description"}).get("content") # 공지 내용은 메타 태그로 저장되어 있음. 페이지 소스 보기로 확인 가능

# Chapter 2: 공지 제목과 내용 따기 end
# Chapter 3: 댓글 따기 start

    # 댓글 페이지 수 계산
    comment_count = soup_unit.find("div", class_="forum_paging_summary ellipsis")
    comment_max = comment_count.text.strip()
    comment_page = int(comment_max.split()[3])//15 + 1 # comment_max.split()[3] = 207은 문자열
    # 스팀 공지 페이지랑 댓글 페이지 보면 공지는 Showing 1-15 of 21 active topics, 댓글은 Showing 1-15 of 214 comments 이런 식으로 공지 수랑 댓글 수가 몇 개인지 보이는데 둘 다 띄어쓰기 기준으로 쪼개면 3번째 인덱스가 최대 갯수임.
    # 한 페이지당 최대 댓글 수가 15개인 걸 이용하여 214/15 이런 식으로 몫을 계산하여 댓글(몫) 페이지 수를 계산, 댓글이 15개보다 적을 경우를 대비해 1을 더해줌-> ctp는 0이 아니라 1부터 시작하기에

    data1 = []
    data2 = []
    data3 = []

    # 댓글 페이지 수 만큼 반복하여 리스트에 댓글 정보를 저장하는 반복문
    for i in range(comment_page):

        comment_comment = soup_unit.find_all("div", class_="commentthread_comment_text")
        comment_name = soup_unit.find_all("bdi")
        comment_date = soup_unit.find_all("span", class_="commentthread_comment_timestamp")

        # 댓글 내용 리스트와 이름 리스트에 각각 저장
        for n in comment_comment:
                data1.append(n.text.strip())
        for m in comment_name:
                data2.append(m.text)
        for o in comment_date:
                data3.append(o.text.strip())

        # 변동되는 ctp에 따라 다시 크롤링 하는 페이지 재정의
        ctp += 1
        res_unit = requests.get(url_unit+str(ctp))
        soup_unit = BeautifulSoup(res_unit.text, "html.parser")


    data_unit = {
        "공지 제목": title_detail,
        "공지 내용": content_detail,
        "댓글 내용": data1,
        "이름": data2,
        "날짜": data3
    }
    data.append(data_unit)

데이터프레임화

In [85]:
# 데이터 프레임으로 변환하고 csv 파일로 저장까지
import pandas as pd

df = pd.DataFrame(data)
df.to_csv("스팀 공지와 반응.csv")
df.head()

,공지 제목,공지 내용,댓글 내용,이름,날짜
0,Patch Version 1.5.12620 Now Live,Patch Notes Added Traditional Chinese translat...,"[, +15 social credit, Hollow Knight update!!! ...","[borsdy, 𝔪𝔢𝔪𝔬𝔯𝔶, tofublockyy⚾, TanKLoveR, Lord...","[26 Mar @ 9:26pm, 26 Mar @ 9:29pm, 26 Mar @ 9:..."
1,Patch Version 1.5.12459 Now Live,Patch Notes Added support for 21:9 & 16:10 res...,[To Team Cherry;I believe that i speak on the ...,"[Cyris™, Pro-Soldier, Pro-Soldier, Vesp, Retro...","[5 Feb @ 3:28pm, 5 Feb @ 3:28pm, 5 Feb @ 3:29p..."
2,Hollow Knight: Silksong Store Page Goes Live!,"Become the Princess KnightAs Hornet, princess-...","[Cool and RARE., , yes, Woah..., YOOOOO, Thank...","[Grey, HEKAU, Sitox, InHomeCalamity, Allar, An...","[14 Feb, 2019 @ 10:23am, 14 Feb, 2019 @ 10:23a..."
3,Update notes for v1.5.78.11833,- Fixed Aspid Hunters and Primal Aspids someti...,"[Real, Actually wild that they're still doing ...","[Toadwinter, Cyrus, 天台好冷啊, Syndiciate, RM_EXE,...","[20 Oct, 2021 @ 10:36pm, 20 Oct, 2021 @ 10:37p..."
4,Cross-platform Cloud Saves,Soon we'll be making some changes in order to ...,"[Oooo, nice. That'll be useful. Thanks for con...","[Noborus, ZzZz, meetnik, Ty Fyter, Mist of Maj...","[10 Aug, 2022 @ 7:30pm, 10 Aug, 2022 @ 7:33pm,..."

1. 가져오는 데이터 양이 많아져서 3-4분씩 걸리니까 확실히 답답해진다  
2. 공지 내용이 띄어쓰기로 연결되서 보기 어렵고 공백 기준으로 쪼개기엔 원문에 띄어쓰기가 있어서 쪼개기가 현실적으로 어렵지만  
지금은 졸려서 자고싶다
3. 공지 내용 가져올 때 메타 태그로 가져왔는데 공지 내용이 메타 태그로만 되어있지 않은 게임도 있었음, 그건 어떻게 해야할 지 감이 안 오지만  
지금은 졸려서 잘 것이다
4. 나중에 댓글 내용, 이름, 날짜를 하나로 묶어야할까? 인덱스 끼리 묶는 함수 뭐 있던데 그거 쓰면 보기에 괜찮아질 지도 모르겠다  
하지만 지금은 졸려서 잘거임